### ISSUE TITLE
[BruteForceTest] ATM기기에 현금이 가득 찼을 때 1000원의 입금을 시도한다.

### ISSUE THREAD

**Issue by kusv2018t1** [kusv2018t1/fantastic-disco#10]

**Comment by aeomhs** [comment]
1,000 / 5,000원 지폐는 소지 한도를 두지 않습니다.
10,000 / 50,000 원 // 10$ / 100$ 의 경우 소지 한도(MAX limit)가 존재하고,
알람이 가는 시기또한 존재합니다.

**Comment by aeomhs** [comment]
또한 10,000 / 50,000 원 // 10$ / 100$ 의 경우 소지 한도에 도달하였을 때에 해당 지폐는 더 이상 입금이 불가합니다.

**Comment by kusv2018t1** [comment]
[SV-MinHwanKim]
@aeomhs 내용 확인하였습니다.
