### ISSUE TITLE
[BruteForceTest]  50달러를 출금한다.

### ISSUE THREAD

**Issue by kusv2018t1** [kusv2018t1/fantastic-disco#12]

**Comment by aeomhs** [comment]
출금에서는 가능한 큰 단위 지폐를 출금하고,
나머지를 작은 단위 지폐로 출금합니다. (큰 단위 지폐가 부족할 경우, 작은 단위 지폐로 모두 출금합니다.)

**Comment by kusv2018t1** [comment]
[SV-MinHwanKim]
기능 정상 작동을 확인하였습니다. Issue close.
